services:
  document-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-document:/var/opt/mssql
      - ./my.cnf:/etc/mysql/my.cnf
  occurrence-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-occurrence:/var/opt/mssql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - document-db
  short-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-short:/var/opt/mssql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - occurrence-db
  medium-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-medium:/var/opt/mssql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - short-word-db
  long-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-long:/var/opt/mssql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - medium-word-db
  word-service:
    build:
      context: .
      dockerfile: WordService/Dockerfile
    deploy:
      replicas: 4
    depends_on:
      - document-db
      - occurrence-db
      - short-word-db
      - medium-word-db
      - long-word-db
  indexer-services:
    build:
      context: .
      dockerfile: Indexer/Dockerfile
  console-services:
    build:
      context: .
      dockerfile: ConsoleSearch/Dockerfile
    depends_on:
      word-service:
        condition: service_started

volumes:
  mssql-data-short:
  mssql-data-medium:
  mssql-data-long:
  mssql-document:
  mssql-occurrence:
