services:
  word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes: 
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
  word-service:
    build:
      context: .
      dockerfile: WordService/Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - word-db
  indexer-services:
    build:
      context: .
      dockerfile: Indexer/Dockerfile
    depends_on:
      - word-service
  console-services:
    build:
      context: .
      dockerfile: ConsoleSearch/Dockerfile
    depends_on:
      - indexer-services

volumes:
  mssql-data:
